
# This function outputs a dataframe all of the drugs in CCLE negatively associated with mutational load into large broad categories.

GetAnnotatedMOA = function() {
    AllDrugs = read.table(paste0(getwd(), '/Data/Regression/AllDrugsOLSRegressionEstimatesKsKaCCLE'), sep=',', header=T, fill=T)
    AllDrugs = subset(AllDrugs, AllDrugs$Coefficient == 'LogScore')
    AllDrugs = subset(AllDrugs, AllDrugs$Estimate < 0)
    # Replace specific drugs with moa categories into more specific groups
    AllDrugs$subgroup[which(AllDrugs$name == "aloe-emodin")] = 'Pro-Apoptosis'
    AllDrugs$subgroup[which(AllDrugs$name == "lenalidomide")] = 'ubiquitin specific protease inhibitor'
    AllDrugs$subgroup[which(AllDrugs$name == "10-deacetylbaccatin")] = 'microtubule inhibitor'
    AllDrugs$subgroup[which(AllDrugs$name == "mitoflaxone")] = 'angiogenesis inhibitor'
    AllDrugs$subgroup[which(AllDrugs$name == "fenspiride")] = 'Inflammatory/Immune'
    AllDrugs$subgroup[which(AllDrugs$name == "ibrutinib")] = 'Pro-Apoptosis'
    AllDrugs$subgroup[which(AllDrugs$name == "CNX-774")] = 'Pro-Apoptosis'  
    AllDrugs$subgroup[which(AllDrugs$name == "acalabrutinib")] = 'Pro-Apoptosis'
    AllDrugs$subgroup[which(AllDrugs$name == "ornithine")] = 'Nitrogen Metabolism Inhibitor'
    AllDrugs$subgroup[which(AllDrugs$name == "heptaminol")] = 'Angiogenesis Activator'
    PlottingGroup = rbind(
        data.frame(PlottingGroup = 'Growth Factor Inhibitors', NewGroup = c('dipeptidyl peptidase inhibitor', 
                                        'EGFR inhibitor',"FGFR inhibitor, VEGFR inhibitor","PDGFR tyrosine kinase receptor inhibitor",'CDK inhibitor, growth factor receptor inhibitor',
                                        "retinoid receptor agonist", 'VEGFR inhibitor','Abl kinase inhibitor, src inhibitor, VEGFR inhibitor','EGFR inhibitor, VEGFR inhibitor',
                                        'EGFR inhibitor, protein tyrosine kinase inhibitor','FLT3 inhibitor, growth factor receptor inhibitor, JAK inhibitor',
                                        'RAF inhibitor, VEGFR inhibitor','tropomyosin receptor kinase inhibitor','PDGFR tyrosine kinase receptor inhibitor, VEGFR inhibitor',
                                        'hepatocyte growth factor receptor inhibitor','insulin growth factor receptor inhibitor','MER tyrosine kinase inhibitor',
                                        'EGFR inhibitor, FGFR inhibitor, FLT3 inhibitor, PDGFR tyrosine kinase receptor inhibitor, VEGFR inhibitor','GK0582 inhibitor',
                                        'FGFR inhibitor, KIT inhibitor, PDGFR tyrosine kinase receptor inhibitor, RAF inhibitor, RET tyrosine kinase inhibitor, VEGFR inhibitor',
                                        'Aurora kinase inhibitor, growth factor receptor inhibitor','bone morphogenic protein inhibitor','growth factor receptor inhibitor')),
        data.frame(PlottingGroup = 'Transport Inhibitor', NewGroup = c('','MRP inhibitor, P glycoprotein inhibitor')),
        data.frame(PlottingGroup = 'Pro-Apoptosis' , NewGroup = c('Pro-Apoptosis',"AKT inhibitor","ALK tyrosine kinase receptor inhibitor","Aurora kinase inhibitor",'CDK inhibitor',
                                        'JNK inhibitor','mTOR inhibitor, PI3K inhibitor','NFkB pathway inhibitor','other antibiotic','phosphodiesterase inhibitor',
                                        'IKK inhibitor, NFkB pathway inhibitor','IKK inhibitor','K-ras inhibitor','KIT inhibitor, VEGFR inhibitor',
                                        'KIT inhibitor, PDGFR tyrosine kinase receptor inhibitor, VEGFR inhibitor','MAP kinase inhibitor','MAP kinase inhibitor, MEK inhibitor',
                                        'MAP kinase phosphatase inhibitor','MET inhibitor','survivin inhibitor','src inhibitor','src inhibitor, syk inhibitor',
                                        'PI3K inhibitor, mTOR inhibitor','mTOR inhibitor','monopolar spindle 1 kinase inhibitor','NAMPT inhibitor',
                                        'protein tyrosine kinase inhibitor, tyrosine kinase inhibitor','tumor necrosis factor production inhibitor','MRP inhibitor, P glycoprotein inhibitor',
                                        'SIRT inhibitor','WEE1 kinase inhibitor','WDR5/MLL interaction inhibitor','vitamin D receptor agonist','phosphoinositide dependent kinase inhibitor',
                                        'protein kinase inhibitor','PKC inhibitor, protein tyrosine kinase inhibitor','MDM inhibitor','serine arginine protein kinase inhibitor',
                                        'tumor necrosis factor receptor antagonist','tyrosine phosphatase inhibitor','Wnt pathway inhibitor','TP53 inhibitor',
                                        'maternal embryonic leucine zipper kinase inhibitor','MEK inhibitor','PARP inhibitor','PKC activator','Ras GTPase inhibitor',
                                        'PI3K inhibitor','PKC inhibitor','PLK inhibitor','protein tyrosine kinase inhibitor','RAF inhibitor','Bcr-Abl kinase inhibitor',
                                        'tyrosine kinase inhibitor','XIAP inhibitor',"ALK tyrosine kinase receptor inhibitor, insulin growth factor receptor inhibitor",
                                        'AKT inhibitor, mTOR inhibitor','AKT inhibitor, MAP kinase inhibitor','AKT inhibitor, pyruvate dehydrogenase inhibitor',
                                        'breast cancer resistance protein inhibitor','caspase activator','carnitine palmitoyltransferase inhibitor',
                                        'thymidine phosphorylase inhibitor','focal adhesion kinase inhibitor','exportin antagonist',
                                        'p21 activated kinase inhibitor','nitric oxide production inhibitor','gap junction modulator, nitric oxide production inhibitor',
                                        'smoothened receptor antagonist','stearoyl-CoA desaturase inhibitor','ornithine decarboxylase inhibitor','mediator release inhibitor, SYK inhibitor',
                                        'DNA protein kinase inhibitor, PI3K inhibitor','FLT3 inhibitor, JAK inhibitor','farnesyltransferase inhibitor',
                                        'FLT3 inhibitor, KIT inhibitor, PDGFR tyrosine kinase receptor inhibitor, RAD51 inhibitor, RET tyrosine kinase inhibitor',
                                        'CDK inhibitor, glycogen synthase kinase inhibitor','CDK inhibitor, FLT3 inhibitor, JAK inhibitor','cFMS kinase inhibitor',
                                        'ALK tyrosine kinase receptor inhibitor, insulin growth factor receptor inhibitor','HDAC inhibitor','ARF inhibitor','BMI-1 inhibitor',
                                        'Aurora kinase inhibitor, JAK inhibitor','BCL inhibitor','BCL inhibitor, MCL1 inhibitor','Bcl-XL downregulator','beta-catenin inhibitor',
                                        'apoptosis stimulant, ribonucleotide reductase inhibitor','apoptosis stimulant','ribonucleotide reductase inhibitor','c-Myc inhibitor',
                                        'DNA damage inducer','CDC inhibitor','ephrin inhibitor','hedgehog pathway inhibitor','HCV inhibitor, XIAP inhibitor',
                                        'telomerase inhibitor','rho associated kinase inhibitor','porcupine inhibitor','phosphoinositide dependent kinase inhibitor',
                                        'Bcr-Abl kinase inhibitor, LYN tyrosine kinase inhibitor','Bcr-Abl kinase inhibitor, FLT3 inhibitor, PDGFR tyrosine kinase receptor inhibitor',
                                        'adenosine deaminase inhibitor, ribonucleotide reductase inhibitor','apoptosis stimulant, NFkB pathway inhibitor','ATM kinase inhibitor',
                                        'casein kinase inhibitor, cell proliferation inhibitor','casein kinase inhibitor, mTOR inhibitor, PI3K inhibitor','casein kinase inhibitor')),
        data.frame(PlottingGroup = 'Anti-Apoptosis' , NewGroup = c('protein tyrosine kinase activator','nitric oxide stimulant','hepatocyte function enhancer',
                                        'src activator','lysophosphatidic acid receptor antagonist','protein kinase activator','p53 activator')),   
        data.frame(PlottingGroup = 'Energy Metabolism Inhibitor' , NewGroup = c("ATPase inhibitor",'ATP synthase inhibitor','AMPK inhibitor','ATP channel blocker',
                                        'ATP synthase inhibitor, ATPase inhibitor','ATP-sensitive potassium channel antagonist','ATPase inhibitor, gastrin inhibitor',
                                        'isocitrate dehydrogenase inhibitor','P glycoprotein inhibitor','pyruvate dehydrogenase kinase inhibitor','NTPDase inhibitor',
                                        'pyruvate dehydrogenase inhibitor',
                                        'ATPase inhibitor, TRPV agonist','ATP channel blocker, insulin secretagogue','autotaxin inhibitor','carbonic anhydrase inhibitor',
                                        'cardiac myosin activator')),
        data.frame(PlottingGroup = 'Inflammatory/Immune' , NewGroup = c('analgesic agent','CC chemokine receptor antagonist','cyclooxygenase inhibitor',
                                        'glucocorticoid receptor agonist','histamine receptor antagonist','histamine receptor agonist','nitric oxide synthase inhibitor','local anesthetic',
                                        'p38 MAPK inhibitor','SYK inhibitor','anti-inflammatory agent, glucocorticoid receptor agonist','antihistamine',
                                        'anti-inflammatory agent','antiinflammatory agent, cyclooxygenase inhibitor','antiinflammatory agent','NOD1 inhibitor',
                                        'macrophage migration inhibiting factor inhibitor','lipoxygenase inhibitor','TGF beta receptor inhibitor',
                                        'TGF beta receptor inhibitor, p38 MAPK inhibitor','MALT1 inhibitor (JH)','mediator release inhibitor','melatonin receptor antagonist',
                                        'metalloproteinase inhibitor','sphingosine 1 phosphate receptor agonist','melanocortin receptor agonist','neprilysin inhibitor',
                                        'matrix metalloprotease inhibitor, tumor necrosis factor production inhibitor',' ediator release inhibitor, SYK inhibitor',
                                        'cyclooxygenase inhibitor, glutathione peroxidase agonist, H+/K+-ATPase inhibitor, nitric oxide synthase inhibitor',
                                        'cyclooxygenase inhibitor, histone acetyltransferase inhibitor, lipoxygenase inhibitor, NFkB pathway inhibitor',
                                        'glycogen synthase kinase inhibitor, lipoxygenase inhibitor','histamine receptor modulator','integrin antagonist',
                                        'cyclooxygenase inhibitor, lipoxygenase inhibitor','corticosteroid agonist','cyclooxygenase inhibitor, prostanoid receptor antagonist',
                                        'cyclooxygenase inhibitor, prostaglandin inhibitor','cyclooxygenase inhibitor, platelet aggregation inhibitor',
                                        'neurotrophic agent','steroid','syk inhibitor',
                                        'STAT inhibitor','prostanoid receptor agonist','prostanoid receptor antagonist','tachykinin antagonist','antitussive',
                                        'cyclooxygenase inhibitor, NFkB pathway inhibitor','cyclooxygenase inhibitor, prostanoid receptor agonist','toll-like receptor antagonist',
                                        'inosine monophosphate dehydrogenase inhibitor','interferon inducer','integrin antagonist','interleukin receptor antagonist, STAT inhibitor',
                                        'interleukin synthesis inhibitor','interleukin inhibitor','JAK inhibitor','JAK inhibitor, STAT inhibitor','JAK inhibitor, syk inhibitor',
                                        'immunosuppressant, inosine monophosphate dehydrogenase inhibitor','immunosuppressant, protein synthesis inhibitor, purine antagonist',
                                        'glutamate inhibitor, macrophage migration inhibiting factor inhibitor','histamine receptor antagonist, platelet activating factor receptor antagonist',
                                        'antioxidant, capillary stabilizing agent, nitric oxide scavenger','antihistamine','calcineurin inhibitor','toll-like receptor agonist',
                                        'leukotriene receptor antagonist, phosphodiesterase inhibitor','leukotriene synthesis inhibitor','NOD1 inhibitor',
                                        'indoleamine 2,3-dioxygenase inhibitor','ICAM1 expression inhibitor','ICAM1 antagonist','leukotriene receptor antagonist',
                                        'CCR antagonist','cytokine production inhibitor','cytokine production inhibitor, NFkB pathway inhibitor, TP53 activator',
                                        'dehydrogenase inhibitor, inositol monophosphatase inhibitor','folate receptor ligand','glucocorticoid receptor agonist, immunosuppressant',
                                        'glucocorticoid receptor antagonist, progesterone receptor antagonist','immunostimulant','immunosuppressant',
                                        'aryl hydrocarbon receptor agonist, indoleamine 2,3-dioxygenase inhibitor')),
        data.frame(PlottingGroup = 'Protein Synthesis Inhibitor' , NewGroup = c('antimalarial agent','bacterial 50S ribosomal subunit inhibitor','protein synthesis inhibitor',
                                        'bacterial 30S ribosomal subunit inhibitor','bacterial 30S ribosomal subunit inhibitor, bacterial 50S ribosomal subunit inhibitor',
                                        'FOXM1 inhibitor, protein synthesis inhibitor','ribosomal protein inhibitor','cytochrome P450 inhibitor, protein synthesis inhibitor',
                                        'cytochrome P450 inhibitor, imidazoline receptor ligand',
                                        'cytochrome P450 inhibitor','eukaryotic translation elongation factor 2 inhibitor','eukaryotic translation initiation factor inhibitor')),
        data.frame(PlottingGroup = 'Protein Synthesis Activator' , NewGroup = c('PERK inhibitor')),
        data.frame(PlottingGroup = 'DNA Replication Inhibitor' , NewGroup = c('antiprotozoal agent','ATR kinase inhibitor','bacterial DNA gyrase inhibitor','CHK inhibitor',
                                        'DNA inhibitor','DNA polymerase inhibitor','topoisomerase inhibitor','bacterial DNA inhibitor','CDK inhibitor, cell cycle inhibitor, MCL1 inhibitor',
                                        'anticancer agent, aryl hydrocarbon receptor antagonist','antiviral','bacterial antifolate','CDK inhibitor, CHK inhibitor, PKC inhibitor',
                                        'purine antagonist',
                                        'DNA alkylating agent, DNA synthesis inhibitor','DNA inhibitor, topoisomerase inhibitor','DNA directed DNA polymerase inhibitor, thymidylate synthase inhibitor',
                                        'DNA alkylating agent, DNA inhibitor','dihydropteroate synthetase inhibitor','DNA directed DNA polymerase inhibitor','dehydrogenase inhibitor',
                                        'DNA alkylating agent','IGF-1 inhibitor','mitotic kinase inhibitor','PABA antagonist','Pim kinase inhibitor','thymidylate synthase inhibitor',
                                        'DNA replication inhibitor, STAT inhibitor','DNA synthesis inhibitor','DNA dependent protein kinase inhibitor','DNA synthesis inhibitor, RNA synthesis inhibitor',
                                        'cell cycle inhibitor, PLK inhibitor','chelating agent, topoisomerase inhibitor','chelating agent','cyclin D inhibitor','dihydrofolate reductase inhibitor',
                                        'dihydropteroate synthase inhibitor','dihydrofolate reductase inhibitor, thymidylate synthase inhibitor','dihydroorotate dehydrogenase inhibitor')),
        data.frame(PlottingGroup = 'Cytoskeleton Organization Inhibitor' , NewGroup = c('bacterial cell wall synthesis inhibitor','fungal lanosterol demethylase inhibitor',
                                        'gap junction modulator','SHIP2 phosphatase inhibitor','sterol demethylase inhibitor','sterol methyltransferase inhibitor','utrophin enhancer',
                                        'kinesin-like spindle protein inhibitor','membrane integrity inhibitor','microtubule inhibitor','beta lactamase inhibitor','DNA intercalating agent',
                                        'microtubule stabilizing agent, tubulin polymerization inhibitor','tubulin polymerization inhibitor','DNA synthesis inhibitor, microtubule inhibitor',
                                        'microtubule stabilizing agent','microtubule inhibitor, tubulin polymerization inhibitor','src inhibitor, tubulin polymerization inhibitor',
                                        'DPRE1 inhibitor','kinesin inhibitor, kinesin-like spindle protein inhibitor','kinesin inhibitor','tubulin polymerization inhibitor, VE-cadherin antagonist',
                                        'bradykinin receptor antagonist, tubulin polymerization inhibitor','penicillin binding protein inhibitor')),
        data.frame(PlottingGroup = 'Transcription Inhibitor' , NewGroup = c('bromodomain inhibitor','RNA polymerase inhibitor','RNA synthesis inhibitor','RNA synthesis inhibitor, topoisomerase inhibitor')),
        data.frame(PlottingGroup = 'Ion Channel Regulation', NewGroup =  c('calcium channel blocker','potassium channel blocker','potassium channel activator','TRPV agonist','TRPV antagonist',
                                        'sodium channel blocker','antiarrhythmic medication','antiarrhythmic','anticestodal agent','calcium sensitizer','calmodulin antagonist',
                                        'calcium receptor antagonist','calcium channel modulator','calcium channel activator','calcium sensitizer, phosphodiesterase inhibitor',
                                        'cardiac glycoside','cationic surfactant','chloride channel blocker','chloride channel antagonist','electrolyte reabsorption inhibitor',
                                        'voltage-gated sodium channel modulator','voltage-gated sodium channel blocker','voltage-gated calcium channel ligand','bacterial permeability inducer',
                                        'succinimide antiepileptic','slow afterhyperpolarization channel blocker','TRPA1 channel blocker','CFTR channel agonist',
                                        'T-type calcium channel binder','T-type calcium channel blocker','sodium/glucose cotransporter inhibitor','sodium/potassium/chloride transporter inhibitor',
                                        'sodium channel blocker, T-type calcium channel blocker',' slow afterhyperpolarization channel blocker','phosphate antagonist',
                                        'potassium channel blocker, sodium channel blocker','N-type calcium channel blocker','Na/K-ATPase inhibitor','mineralocorticoid receptor agonist',
                                        'mineralocorticoid receptor antagonist','potassium-competitive acid antagonist','serum/glucocorticoid regulated kinase inhibitor',
                                        'phosphodiesterase inhibitor, sodium channel blocker','nitric oxide donor, potassium channel activator','nitric oxide donor',
                                        'electrolyte reabsorption inhibitor, thromboxane receptor antagonist','electrolyte reabsorption inhibitor, thromboxane receptor antagonist',
                                        'collapsin response mediator protein inhibitor, collapsin response mediator protein stimulant, sodium channel blocker','Kir6 channel (KATP) activator',
                                        'HCN channel antagonist, potassium channel blocker, sodium channel blocker','HCN channel blocker','hydantoin antiepileptic','thiazide diuretic',
                                        'L-type calcium channel activator','L-type calcium channel blocker','KATP activator, Kir6 channel (KATP) activator, vasodilator','vasoconstrictor',
                                        'glutamate inhibitor','glutamate receptor antagonist, calcium channel blocker','glutamate receptor modulator','ionotropic receptor IR40a activator',
                                        'glutamate receptor negative allosteric modulator',' glutamate receptor positive allosteric modulator','intermediate conductance potassium channel blocker',
                                        'chloride channel agonist, benzodiazepine receptor agonist','chloride reabsorption inhibitor','electron acceptor','membrane permeability inhibitor',
                                        'chloride channel activator','chloride channel blocker, gap junction modulator, glutamate inhibitor')),
        data.frame(PlottingGroup = 'Protein Degradation Inhibitors', NewGroup =  c("HCV inhibitor",'HIV protease inhibitor',"proteasome inhibitor",'ubiquitin specific protease inhibitor',
                                        'NFkB pathway inhibitor, proteasome inhibitor','ubiquitin C-terminal hydrolase inhibitor','ubiquitin-conjugating enzyme inhibitor',
                                        'deubiquitinase inhibitor','cysteine protease inhibitor, calpain inhibitor','DUB inhibitor','nedd activating enzyme inhibitor')),
        data.frame(PlottingGroup = 'Chaperone Inhibitors', NewGroup =  c("HSP inhibitor",'HSP antagonist')),
        data.frame(PlottingGroup = 'Chaperone Activators', NewGroup =  c("HSP inducer")),
        data.frame(PlottingGroup = 'Oxidative Stress Activator', NewGroup =  c("gamma glutamyltransferase Inhibitors",'glucose dependent insulinotropic receptor agonist',
                                        'mitochondrial electron transport inhibitor','oxidative stress inducer','MTH1 inhibitor','superoxide dismutase inhibitor')),
        data.frame(PlottingGroup = 'Lipid Metabolism Inhibitor', NewGroup = c('3-ketoacyl CoA thiolase inhibitor','ACAT inhibitor','atherogenesis inhibitor','cholesteryl ester transfer protein inhibitor',
                                        'ACAT inhibitor, sterol regulatory element binding protein (SREBP) inhibitor','adipose triglyceride lipase inhibitor','cholesterol inhibitor',
                                        'lipase inhibitor','lipid peroxidase inhibitor','microsomal trigylceride transfer protein inhibitor','phosphatidylglycerophosphatase inhibitor',
                                        'fatty acid synthase inhibitor','11-beta hydroxysteroid dehydrogenase inhibitor, FXR agonist','FXR agonist','phospholipase inhibitor',
                                        'diacylglycerol kinase inhibitor, protein kinase inhibitor','PPAR receptor antagonist',
                                        'PKA inhibitor','PPAR receptor agonist','secretory phospholipase inhibitor','oxidosqualene cyclase inhibitor','omega 3 fatty acid stimulant',
                                        'cholesterol inhibitor, Niemann-Pick C1-like 1 protein antagonist','diacylglycerol O acyltransferase inhibitor')),
        data.frame(PlottingGroup = 'Lipid Metabolism Activator', NewGroup = c('apolipoprotein expression enhancer','constitutive androstane receptor (CAR) agonist','FABI inhibitor',
                                        'lipoprotein lipase activator','LDL receptor activator','monoacylglucerol lipase inhibitor','mycolic synthesis inhibitor',
                                        'phospholipase activator',
                                        'free fatty acid receptor agonist','fungal squalene epoxidase inhibitor','gamma secretase inhibitor','gamma secretase modulator','coenzyme A precursor')),
        data.frame(PlottingGroup = 'Growth Hormone Inhibitor', NewGroup = c('5 alpha reductase inhibitor','androgen receptor antagonist', "progesterone receptor agonist",'adenylyl cyclase inhibitor',
                                        'androgen biosynthesis inhibitor','androgen receptor agonist','androgen receptor agonist, estrogen receptor agonist',
                                        'aromatase inhibitor, TRPV antagonist','estrogen receptor agonist','estrogen receptor agonist, estrogenic hormone',
                                        'somatostatin receptor agonist',
                                        'thyrotropin releasing hormone receptor agonist','thyroid hormone inhibitor','selective estrogen receptor destabilizer',
                                        'progesterone receptor antagonist','prostaglandin inhibitor','prostaglandin receptor agonist','prostaglandin synthesis inhibitor',
                                        'estrogen receptor antagonist, selective estrogen receptor modulator (SERM)','estrogen receptor antagonist','estrogen-related receptor agonist',
                                        'estrogenic hormone','estrogen receptor antagonist, progesterone receptor agonist','GLP receptor agonist','progestogen hormone',
                                        'gonadotropin releasing factor hormone receptor antagonist','steroid sulfatase inhibitor','selective estrogen receptor modulator (SERM)',
                                        'growth hormone secretagogue receptor agonist','gonadotropin releasing factor hormone receptor agonist','gonadotropin inhibitor',
                                        'estrogen receptor agonist, glucocorticoid receptor antagonist, progesterone receptor agonist, progesterone receptor antagonist',
                                        'androgen receptor agonist, estrogen receptor agonist, progesterone receptor agonist','aromatase inhibitor','calcitonin antagonist')),
        data.frame(PlottingGroup = 'Growth Hormone Activator', NewGroup = c('androgen receptor enhancer',' androgen receptor modulator','thyroid hormone stimulant')),
        data.frame(PlottingGroup = 'Angiogenesis Inhibitor', NewGroup = c('angiogenesis inhibitor','angiogenesis inhibitor, tumor necrosis factor production inhibitor',
                                        'endothelin receptor antagonist','hypoxia inducible factor inhibitor','matrix metalloprotease inhibitor','P selectin inhibitor',
                                        'platelet aggregation inhibitor','platelet activating factor receptor antagonist','thromboxane receptor antagonist',
                                        'vasopressin receptor agonist','vasopressin receptor antagonist',
                                        'thrombopoietin receptor agonist','vitamin K antagonist','coagulation factor inhibitor','plasminogen activator inhibitor',
                                        'thromboxane receptor antagonist, thromboxane synthase inhibitor','thromboxane receptor antagonist','thrombin inhibitor',
                                        'angiotensin antagonist','angiotensin converting enzyme inhibitor','angiotensin receptor agonist','angiotensin receptor antagonist',
                                        'bradykinin receptor antagonist','phosphodiesterase inhibitor, platelet aggregation inhibitor','thromboxane synthase inhibitor')),
        data.frame(PlottingGroup = 'Angiogenesis Activator', NewGroup = c('renin inhibitor','haemostatic agent')),                         
        data.frame(PlottingGroup = 'Neurotransmitter Inhibitor', NewGroup = c('acetylcholine receptor agonist','acetylcholine receptor agonist, benzodiazepine receptor agonist',
                                        'acetylcholine receptor allosteric modulator', 'dopamine receptor agonist','dopamine receptor antagonist','cholinergic receptor antagonist',
                                        'cholinesterase inhibitor','cholinesterase reactivator','cholinergic receptor agonist','dopamine receptor agonist, serotonin receptor antagonist',
                                        'dopamine receptor ligand','dopamine beta hydroxylase inhibitor','dopamine uptake inhibitor','dopamine reuptake inhibitor, serotonin reuptake inhibitor',
                                        'dopamine reuptake inhibitor','dopamine receptor partial agonist','dopamine reuptake inhibitor, selective serotonin reuptake inhibitor (SSRI)',
                                        'sigma receptor agonist','sigma receptor agonist, sigma receptor antagonist','sigma receptor antagonist','sigma receptor ligand',
                                        'nicotinic receptor agonist','norepinephrine reuptake inhibitor, serotonin-norepinephrine reuptake inhibitor (SNRI)',
                                        'norepinephrine reuptake inhibitor, serotonin-norepinephrine reuptake inhibitor (SNRI), tricyclic antidepressant',
                                        'neuromuscular blocker','opioid receptor agonist','opioid receptor agonist, opioid receptor antagonist','opioid receptor antagonist',
                                        'opioid receptor modulator','purinergic receptor antagonist','tricyclic antidepressant','sedative',
                                        'norepinephrine transporter inhibitor','norepinephrine reuptake inhibitor','trace amine associated receptor agonist',
                                        'norepinephrine reputake inhibitor, opioid receptor agonist, serotonin reuptake inhibitor','norepinephrine reputake inhibitor, tricyclic antidepressant',
                                        'norepinephrine reputake inhibitor','noradrenaline uptake inhibitor','nootropic agent','tyrosine hydroxylase inhibitor',
                                        'vesicular monoamine transporter inhibitor','neuropeptide receptor antagonist','tryptophan hydroxylase inhibitor','antispasmodic',
                                        'norepinephrine inhibitor, norepinephrine reuptake inhibitor, serotonin receptor antagonist, serotonin-norepinephrine reuptake inhibitor (SNRI)',
                                        'melatonin receptor agonist','serotonin transporter (SERT) inhibitor','serotonin reuptake inhibitor','serotonin receptor agonist, serotonin receptor antagonist',
                                        'dopamine-norepinephrine reuptake inhibitor','excitatory amino acid transporter inhibitor','GABA receptor antagonist, GABA receptor modulator',
                                        'GABA benzodiazepine site receptor inverse agonist','GABA benzodiazepine site receptor agonist','GABA aminotransferase inhibitor','GABA uptake inhibitor',
                                        'GABA uptake inhibitor, GAT inhibitor','GABA receptor modulator','GABA receptor antagonist','GABA receptor negative allosteric modulator',
                                        'GABA receptor antagonist, serotonin receptor antagonist','GABA transaminase inhibitor','gamma hydroxybutyric acid ligand','imidazoline receptor antagonist',
                                        'Glycine transporter 1 inhibitor','glycine transporter inhibitor, GlyT-1 inhibitor','GAT inhibitor','imidazoline receptor agonist',
                                        'neurotransmitter agonist','orexin receptor antagonist','oxytocin receptor antagonist','serotonin-norepinephrine reuptake inhibitor (SNRI)',
                                        'kainate receptor agonist','serotonin receptor agonist, dopamine receptor agonist','selective serotonin reuptake inhibitor (SSRI)',
                                        'dopamine receptor antagonist, serotonin receptor antagonist',"acetylcholine receptor antagonist","adenosine receptor antagonist","adenosine receptor agonist",
                                        "adrenergic receptor agonist","adrenergic receptor antagonist",'benzodiazepine receptor agonist',"glutamate receptor antagonist",'cannabinoid receptor antagonist',
                                        'serotonin receptor agonist','serotonin receptor antagonist','acetylcholinesterase inhibitor','acetylcholinesterase inhibitor, beta amyloid synthesis inhibitor',
                                        'acetylcholinesterase inhibitor, microtubule inhibitor','acetylcholinesterase inhibitor, monoamine oxidase inhibitor',' barbiturate antiepileptic, GABA receptor modulator',
                                        "adenosine receptor antagonist, hemoglobin antagonist",'adenosine receptor antagonist, phosphodiesterase inhibitor','anxiolytic','barbiturate antiepileptic, GABA receptor modulator',
                                        'adenosine reuptake inhibitor, phosphodiesterase inhibitor','adrenergic receptor agonist, dopamine receptor agonist','anticonvulsant','cannabinoid receptor agonist',
                                        'adrenergic receptor agonist, serotonin receptor agonist','benzodiazepine receptor antagonist','benzodiazepine receptor ligand','barbiturate antiepileptic, GABA receptor modulator',
                                        'adrenergic receptor antagonist, glutamate receptor antagonist','adrenergic receptor ligand','adrenergic inhibitor','anthelmintic agent',' cannabinoid receptor inverse agonist',
                                        'cannabinoid receptor inverse agonist','cannabinoid receptor agonist, glucose dependent insulinotropic receptor agonist, potassium channel blocker, PPAR receptor agonist',
                                        'beta amyloid protein neurotoxicity inhibitor','FAAH inhibitor','FAAH inhibitor, FAAH reuptake inhibitor','glutamate receptor agonist','imidazoline receptor ligand',
                                        'cannabinoid receptor modulator','catechol O methyltransferase inhibitor')),
        data.frame(PlottingGroup = 'Neurotransmitter Enhancer', NewGroup = c('acetylcholine release enhancer','androgen receptor modulator','barbiturate antiepileptic, GABA receptor modulator',
                                        'enkephalinase inhibitor','glutamate receptor positive allosteric modulator','monoamine oxidase inhibitor')),
        data.frame(PlottingGroup = 'Oxidative Stress Inhibitors', NewGroup = c('antioxidant', "nuclear factor erythroid derived, like (NRF2) activator",'11-beta hydroxysteroid dehydrogenase inhibitor',
                                        'free radical scavenger','flavanone glycoside','glutathione transferase stimulant','NADPH oxidase inhibitor','NADPH inhibitor','melanin inhibitor',
                                        'RAGE receptor antagonist','NAD precursor, vitamin B','xanthine oxidase inhibitor')),                          
        data.frame(PlottingGroup = 'Other', NewGroup = c('antacid','antiinfective drug','levodropropizine','bone resorption inhibitor','contrast agent','expectorant','laxative','topical sunscreen agent',
                                        'topical anesthetic','radiopaque medium','psychoactive drug','antiseptic','mucolytic agent','mucus protecting agent','antiseptic','choleretic agent','pharmacological chaperone',
                                        'panipenem uptake inhibitor','pregnane X receptor agonist','tyrosinase inhibitor','protein synthesis stimulant',
                                        'solute carrier family member inhibitor','transthyretin amyloid inhibitor','anti-pneumocystis agent',
                                        'gene expression stimulant','hypercalcaemic agent','motilin receptor agonist','muscle relaxant','myorelaxant','nematocide','osmosis stimulant', 'other antifungal',
                                        'cosmetic','cosmetic moisturizer','coloring agent','caspase inhibitor','contraceptive agent','excipient','enzyme inducer','growth factor receptor activator')),
        data.frame(PlottingGroup = 'Histone/Methylation Inhibitor', NewGroup = c('adenosylhomocysteinase inhibitor','DNA methyltransferase inhibitor','histone lysine methyltransferase inhibitor',
                                        'L3MBTL antagonist')),
        data.frame(PlottingGroup = 'Alcohol Metabolism Inhibitor', NewGroup = c('alcohol dehydrogenase inhibitor')),
        data.frame(PlottingGroup = 'Sugar Metabolism Inhibitor', NewGroup = c('aldose reductase inhibitor','alpha mannosidase inhibitor','fungal 1,3-beta-D-glucan synthase inhibitor',
                                        'glucokinase inhibitor','glucosidase inhibitor','glycolysis inhibitor','insulin sensitizer, PPAR receptor agonist','insulin sensitizer',
                                        'thiamine uptake blocker','neprilysin','hypercalcaemic','sulfonylurea',
                                        'insulin secretagogue','phosphofructokinase inhibitor','niacinamide phosphoribosyltransferase inhibitor','neuraminidase inhibitor')),
        data.frame(PlottingGroup = 'Sugar Metabolism Activator', NewGroup = c('glucokinase activator','glucagon receptor antagonist','glycogen synthase kinase inhibitor',
                                        'phosphoenolpyruvate carboxylase activator, serine/threonine protein phosphatase activator')),
        
        data.frame(PlottingGroup = 'G-Coupled Receptor Regulator', NewGroup = c('aryl hydrocarbon receptor antagonist','aryl hydrocarbon receptor agonist, indoleamine 2,3-dioxygenase inhibitor',
                                        'CCK receptor agonist','CCK receptor antagonist','G protein-coupled receptor agonist','guanylate cyclase stimulant','guanylate cyclase activator',
                                        'IP1 prostacyclin receptor agonist','neurokinin receptor antagonist','protease-activated receptor inhibitor','nociceptin/orphanin FQ receptor antagonist')),
        data.frame(PlottingGroup = 'Protein Metabolism Inhibitor', NewGroup =  c("aspartic protease inhibitor",'beta-secretase inhibitor','cathepsin inhibitor','collagenase inhibitor',
                                        'collagenase inhibitor, metalloproteinase inhibitor','collagenase inhibitor','glycosylation inhibitor','Glycosyl transferase inhibitor',
                                        'Procollagen C-Endopeptidase Inhibitors','vitamin B','protease inhibitor','serine protease inhibitor',
                                        'hydroxyphenylpyruvate dioxygenase inhibitor','peptidase inhibitor','methylmalonyl CoA mutase stimulant, vitamin B','mannosidase inhibitor',
                                        'HCV inhibitor, protease inhibitor','elastase inhibitor','HMGCR inhibitor')),
        data.frame(PlottingGroup = 'Nitrogen Metabolism Inhibitor', NewGroup =  c('carbamoyl phosphate synthase activator','urate transporter inhibitor',
                                        'urease inhibitor','uricase inhibitor','uricosuric blocker')),
        data.frame(PlottingGroup = 'Viral Replication Inhibitor', NewGroup = c('nucleoside reverse transcriptase inhibitor','non-nucleoside reverse transcriptase inhibitor',
                                        'HIV attachment inhibitor','HIV integrase inhibitor','RSV fusion inhibitor'))
    )
    return(merge(AllDrugs, PlottingGroup, by.x='subgroup', by.y='NewGroup', all.x=T))
}


